version: '3.8'

services:

  db:
    image: mysql:latest
    container_name: projeto-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: projeto_santander_coders
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/java/com/projeto/ada/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro